<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AI_WatcherThread.Runtime\AI_WatcherThread.Runtime.csproj" />
    <ProjectReference Include="..\..\Core_Health\Core_Health.Domain\Core_Health.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


</Project>
